
GET http://localhost:3335/nestjs-full-scaffold/env-example?duration=3000
###
GET http://localhost:3335/nestjs-full-scaffold/env-example?duration=30


###
GET http://localhost:3335/nestjs-full-scaffold/throw-http-exception-of-403

###
GET http://localhost:3335/nestjs-full-scaffold/env-example-use-raw-response?x=2

###
GET http://localhost:3335/nestjs-full-scaffold/should-return-not-found

###
GET http://localhost:3335/nestjs-full-scaffold/benchmark/hello-world

###
GET http://localhost:3335/nestjs-full-scaffold/publish-mqtt-message

###
GET http://localhost:3335/nestjs-full-scaffold/publish-redis-message?x=2
###
GET http://localhost:3335/nestjs-full-scaffold/get-data-auto-cache-response