# docker-compose up -d
# docker-compose down
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    volumes:
      - ../:/usr/src/app
    env_file:
    - ../.env
    # Run a command against the development stage of the image
    command: npm run start:dev
    ports:
      - 3333:3333